/**
 * Agent bearer tokens (FR-4, FR-7).
 *
 * ## The plaintext shape, and why it has an id in it
 *
 *     dl_<row uuid>_<64 lowercase hex characters>
 *
 * i1 recommended this in the `agent_token` table comment and the reason is a
 * real one: without an id in the token, verifying a bearer credential means
 * bcrypt-comparing the presented secret against **every stored hash** on every
 * request. bcrypt at cost 12 is ~250ms by design, so an O(n) verification is
 * both a latency problem and an unauthenticated CPU-exhaustion surface. With the
 * id, verification is one indexed lookup and exactly one bcrypt comparison.
 *
 * The id is not the secret. It is a random uuid that the operator can already
 * see in the token list, and possessing it grants nothing.
 *
 * ## Only the secret segment is hashed, and this is deliberate
 *
 * pgcrypto's `crypt(…, gen_salt('bf', …))` is Blowfish, which **silently
 * truncates its input at 72 bytes**. The full plaintext above is 104 characters,
 * so hashing the whole string would put 32 characters of the secret past the
 * truncation boundary where they contribute nothing — a credential that looks
 * like it has 256 bits of entropy and actually has fewer. Hashing the 64-byte
 * secret segment alone sits under the limit with nothing discarded. The
 * truncation is verified by observation in the unit report rather than taken on
 * faith.
 *
 * ## Entropy
 *
 * 32 bytes from `crypto.getRandomValues` → 256 bits, rendered as 64 hex
 * characters. Hex rather than base64url on purpose: base64url's alphabet
 * includes `_`, which is this format's separator, and a separator that can
 * appear inside a field is a parser bug waiting to happen.
 */

/** The literal prefix every token carries, so one is recognisable on sight. */
export const AGENT_TOKEN_PREFIX = "dl";

/** Bytes of randomness in the secret segment. */
export const AGENT_TOKEN_SECRET_BYTES = 32;

const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const SECRET_PATTERN = /^[0-9a-f]{64}$/;

export interface AgentTokenParts {
  /** `agent_token.id` — the row to look up. Not secret. */
  id: string;
  /** The 64-hex-character secret. **This is the credential.** Never log it. */
  secret: string;
}

export interface MintedAgentToken extends AgentTokenParts {
  /**
   * The full `dl_<id>_<secret>` string.
   *
   * Spec §7a: shown once at creation and never stored. It must not reach a log,
   * a report, a fixture, a screenshot or an audit row.
   */
  plaintext: string;
}

function randomHex(bytes: number): string {
  const buffer = new Uint8Array(bytes);
  crypto.getRandomValues(buffer);
  return Array.from(buffer, (byte) => byte.toString(16).padStart(2, "0")).join(
    "",
  );
}

/**
 * Build a new token plaintext for a row id the caller has already generated.
 *
 * The id is generated by the caller rather than by the database default so that
 * the token can be assembled before the INSERT — the alternative is inserting,
 * reading the id back, and updating the hash, which leaves a window in which a
 * row exists with a hash that verifies nothing.
 */
export function mintAgentToken(id: string): MintedAgentToken {
  if (!UUID_PATTERN.test(id)) {
    throw new Error(
      `mintAgentToken requires a lowercase uuid for the row id; got ${JSON.stringify(id)}.`,
    );
  }
  const secret = randomHex(AGENT_TOKEN_SECRET_BYTES);
  return { id, secret, plaintext: `${AGENT_TOKEN_PREFIX}_${id}_${secret}` };
}

/** Generate a row id and its token in one step. */
export function mintAgentTokenWithNewId(): MintedAgentToken {
  return mintAgentToken(crypto.randomUUID());
}

/**
 * Parse an untrusted token string.
 *
 * Returns `null` for anything that is not exactly the expected shape — wrong
 * prefix, wrong segment count, a uuid that is not a uuid, a secret that is not
 * 64 hex characters. It never partially accepts and never guesses, because the
 * only thing downstream of this function is a credential check.
 *
 * Rejecting on shape before touching the database also means a malformed
 * `Authorization` header costs one regex rather than a query.
 */
export function parseAgentToken(raw: unknown): AgentTokenParts | null {
  if (typeof raw !== "string") return null;

  const segments = raw.split("_");
  if (segments.length !== 3) return null;

  const [prefix, id, secret] = segments;
  if (prefix !== AGENT_TOKEN_PREFIX) return null;
  if (!UUID_PATTERN.test(id)) return null;
  if (!SECRET_PATTERN.test(secret)) return null;

  return { id, secret };
}

/**
 * Pull the credential out of an `Authorization` header.
 *
 * The scheme comparison is case-insensitive because RFC 7235 says the scheme
 * token is, and a client sending `bearer` lowercase is following the spec, not
 * attacking us. Everything after the scheme is treated as opaque and handed to
 * `parseAgentToken`, which is the only thing that decides whether it is a token.
 */
export function bearerFromAuthorizationHeader(
  header: string | null | undefined,
): string | null {
  if (typeof header !== "string") return null;
  const match = /^Bearer[ \t]+(\S+)[ \t]*$/i.exec(header.trim());
  return match ? match[1] : null;
}

/**
 * A redaction helper for anywhere a token might otherwise be printed.
 *
 * It returns the **id only** — never a prefix of the secret. A truncated
 * credential in a transcript is still a credential in a transcript, and this
 * project's rules say so in those words.
 */
export function describeTokenForLog(parts: AgentTokenParts | null): string {
  return parts ? `agent_token:${parts.id}` : "unauthenticated";
}
