// Generated by `generate_typescript_types` against Supabase project
// onpvolboecjpdkvurjaf on 2026-08-19 (fleet run b0952e, work-unit i1;
// audit_log's capability/endpoint/outcome/status columns added by i4's
// 20260819162731_audit_log_fr6_columns migration and re-generated then).
//
// DO NOT EDIT BY HAND. Regenerate after any migration.
//
// ONE DOCUMENTED EXCEPTION, hand-applied by work-unit i5 of run b0952e.
// Migration 20260819165903_i5_ingest_idempotency_and_gates adds
// `open_question.source_key` (text) and `fleet_run.gates` (jsonb, NOT NULL
// default '{}') plus `fleet_run.tests_passed/tests_failed/tests_skipped` (int).
// Those five columns were added to this file BY HAND rather than by
// regenerating, because i5, i6 and i8 were building in parallel worktrees and
// three concurrent regenerations conflict irreconcilably. The next legitimate
// regeneration supersedes this note and should reproduce all five columns
// identically — if it does not, the migration did not apply, and that is the
// finding rather than a types problem.
//
// `audit_log.capability` is `string`, not the `agent_capability` enum, and that
// is deliberate: it stores FR-5's WIRE spelling (`answer:read`) rather than the
// enum's (`answer_read`), pinned by a check constraint. See the migration.
//
// One trap worth knowing before you use these types: every pgcrypto-encrypted
// column (spec 7a) is `bytea` in Postgres and surfaces here as `string | null`,
// because PostgREST serialises bytea as a `\x`-prefixed hex string. That string
// is CIPHERTEXT, not plaintext and not a Buffer. Rendering it directly puts hex
// on the screen; it never leaks the value, but it is never the value either.
//
// The encrypted columns are:
//   contract_milestone.amount, contract_milestone.notes
//   requirement.text
//   work_item.description, work_item.raw_status
//   work_session.summary
//   blocker.description
//   open_question.question, open_question.best_guess, open_question.answer
//   defect.description, defect.wont_fix_reason
//
// Read them through the `decrypt_field` RPC with the service-role client, which
// is the only role granted EXECUTE on it. `agent_token.token_hash` is different
// again: it is a bcrypt hash, not ciphertext, and nothing ever reads it back.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.15"
  }
  public: {
    Tables: {
      acceptance_criterion: {
        Row: {
          id: string
          milestone_id: string
          requirement_ref: string
        }
        Insert: {
          id?: string
          milestone_id: string
          requirement_ref: string
        }
        Update: {
          id?: string
          milestone_id?: string
          requirement_ref?: string
        }
        Relationships: [
          {
            foreignKeyName: "acceptance_criterion_milestone_id_fkey"
            columns: ["milestone_id"]
            isOneToOne: false
            referencedRelation: "contract_milestone"
            referencedColumns: ["id"]
          },
        ]
      }
      agent_token: {
        Row: {
          capabilities: Database["public"]["Enums"]["agent_capability"][]
          created_at: string
          expires_at: string
          id: string
          label: string
          last_used_at: string | null
          revoked_at: string | null
          token_hash: string
        }
        Insert: {
          capabilities?: Database["public"]["Enums"]["agent_capability"][]
          created_at?: string
          expires_at: string
          id?: string
          label: string
          last_used_at?: string | null
          revoked_at?: string | null
          token_hash: string
        }
        Update: {
          capabilities?: Database["public"]["Enums"]["agent_capability"][]
          created_at?: string
          expires_at?: string
          id?: string
          label?: string
          last_used_at?: string | null
          revoked_at?: string | null
          token_hash?: string
        }
        Relationships: []
      }
      audit_log: {
        Row: {
          action: string
          actor: string | null
          actor_type: Database["public"]["Enums"]["actor_type"]
          capability: string | null
          created_at: string
          endpoint: string | null
          id: number
          outcome: string | null
          status: number | null
          target_id: string | null
          target_table: string | null
        }
        Insert: {
          action: string
          actor?: string | null
          actor_type: Database["public"]["Enums"]["actor_type"]
          capability?: string | null
          created_at?: string
          endpoint?: string | null
          id?: never
          outcome?: string | null
          status?: number | null
          target_id?: string | null
          target_table?: string | null
        }
        Update: {
          action?: string
          actor?: string | null
          actor_type?: Database["public"]["Enums"]["actor_type"]
          capability?: string | null
          created_at?: string
          endpoint?: string | null
          id?: never
          outcome?: string | null
          status?: number | null
          target_id?: string | null
          target_table?: string | null
        }
        Relationships: []
      }
      blocker: {
        Row: {
          description: string | null
          disposition: Database["public"]["Enums"]["work_disposition"] | null
          engagement_id: string
          id: string
          opened_at: string | null
          owner: string | null
          ref: string | null
          resolved_at: string | null
        }
        Insert: {
          description?: string | null
          disposition?: Database["public"]["Enums"]["work_disposition"] | null
          engagement_id: string
          id?: string
          opened_at?: string | null
          owner?: string | null
          ref?: string | null
          resolved_at?: string | null
        }
        Update: {
          description?: string | null
          disposition?: Database["public"]["Enums"]["work_disposition"] | null
          engagement_id?: string
          id?: string
          opened_at?: string | null
          owner?: string | null
          ref?: string | null
          resolved_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "blocker_engagement_id_fkey"
            columns: ["engagement_id"]
            isOneToOne: false
            referencedRelation: "engagement"
            referencedColumns: ["id"]
          },
        ]
      }
      contract_milestone: {
        Row: {
          amount: string | null
          currency: string
          due_date: string | null
          engagement_id: string
          id: string
          name: string
          notes: string | null
          paid_at: string | null
          submitted_at: string | null
        }
        Insert: {
          amount?: string | null
          currency?: string
          due_date?: string | null
          engagement_id: string
          id?: string
          name: string
          notes?: string | null
          paid_at?: string | null
          submitted_at?: string | null
        }
        Update: {
          amount?: string | null
          currency?: string
          due_date?: string | null
          engagement_id?: string
          id?: string
          name?: string
          notes?: string | null
          paid_at?: string | null
          submitted_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contract_milestone_engagement_id_fkey"
            columns: ["engagement_id"]
            isOneToOne: false
            referencedRelation: "engagement"
            referencedColumns: ["id"]
          },
        ]
      }
      defect: {
        Row: {
          description: string | null
          engagement_id: string
          fixing_work_item_id: string | null
          id: string
          ref: string
          reported_at: string
          reported_by: string | null
          requirement_ref: string | null
          severity: Database["public"]["Enums"]["defect_severity"]
          source: Database["public"]["Enums"]["defect_source"]
          status: Database["public"]["Enums"]["defect_status"]
          title: string
          verified_at: string | null
          wont_fix_reason: string | null
        }
        Insert: {
          description?: string | null
          engagement_id: string
          fixing_work_item_id?: string | null
          id?: string
          ref: string
          reported_at?: string
          reported_by?: string | null
          requirement_ref?: string | null
          severity?: Database["public"]["Enums"]["defect_severity"]
          source: Database["public"]["Enums"]["defect_source"]
          status?: Database["public"]["Enums"]["defect_status"]
          title: string
          verified_at?: string | null
          wont_fix_reason?: string | null
        }
        Update: {
          description?: string | null
          engagement_id?: string
          fixing_work_item_id?: string | null
          id?: string
          ref?: string
          reported_at?: string
          reported_by?: string | null
          requirement_ref?: string | null
          severity?: Database["public"]["Enums"]["defect_severity"]
          source?: Database["public"]["Enums"]["defect_source"]
          status?: Database["public"]["Enums"]["defect_status"]
          title?: string
          verified_at?: string | null
          wont_fix_reason?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "defect_engagement_id_fkey"
            columns: ["engagement_id"]
            isOneToOne: false
            referencedRelation: "engagement"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "defect_fixing_work_item_id_fkey"
            columns: ["fixing_work_item_id"]
            isOneToOne: false
            referencedRelation: "work_item"
            referencedColumns: ["id"]
          },
        ]
      }
      engagement: {
        Row: {
          archived_at: string | null
          client_name: string
          contract_type: string | null
          created_at: string
          db_org: string | null
          db_project_ref: string | null
          fleet_dir: string | null
          hosting_project: string | null
          hosting_team: string | null
          id: string
          production_url: string | null
          repo_path: string | null
          slug: string
          source: string | null
          spec_path: string | null
          stacks: string[]
          status: string
        }
        Insert: {
          archived_at?: string | null
          client_name: string
          contract_type?: string | null
          created_at?: string
          db_org?: string | null
          db_project_ref?: string | null
          fleet_dir?: string | null
          hosting_project?: string | null
          hosting_team?: string | null
          id?: string
          production_url?: string | null
          repo_path?: string | null
          slug: string
          source?: string | null
          spec_path?: string | null
          stacks?: string[]
          status?: string
        }
        Update: {
          archived_at?: string | null
          client_name?: string
          contract_type?: string | null
          created_at?: string
          db_org?: string | null
          db_project_ref?: string | null
          fleet_dir?: string | null
          hosting_project?: string | null
          hosting_team?: string | null
          id?: string
          production_url?: string | null
          repo_path?: string | null
          slug?: string
          source?: string | null
          spec_path?: string | null
          stacks?: string[]
          status?: string
        }
        Relationships: []
      }
      external_wait: {
        Row: {
          engagement_id: string
          expected_by: string | null
          id: string
          label: string
          owner: string | null
          owner_type: string | null
          probe_target: string | null
          reason: string | null
          resolution_method:
            | Database["public"]["Enums"]["wait_resolution_method"]
            | null
          resolved_at: string | null
          resolved_by: string | null
          started_at: string | null
        }
        Insert: {
          engagement_id: string
          expected_by?: string | null
          id?: string
          label: string
          owner?: string | null
          owner_type?: string | null
          probe_target?: string | null
          reason?: string | null
          resolution_method?:
            | Database["public"]["Enums"]["wait_resolution_method"]
            | null
          resolved_at?: string | null
          resolved_by?: string | null
          started_at?: string | null
        }
        Update: {
          engagement_id?: string
          expected_by?: string | null
          id?: string
          label?: string
          owner?: string | null
          owner_type?: string | null
          probe_target?: string | null
          reason?: string | null
          resolution_method?:
            | Database["public"]["Enums"]["wait_resolution_method"]
            | null
          resolved_at?: string | null
          resolved_by?: string | null
          started_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "external_wait_engagement_id_fkey"
            columns: ["engagement_id"]
            isOneToOne: false
            referencedRelation: "engagement"
            referencedColumns: ["id"]
          },
        ]
      }
      fleet_run: {
        Row: {
          branch: string | null
          dispatch_cap: number | null
          dispatches_used: number | null
          ended_at: string | null
          engagement_id: string
          gates: Json
          id: string
          mode: string | null
          run_id: string
          started_at: string | null
          tests_failed: number | null
          tests_passed: number | null
          tests_skipped: number | null
          verdict: string | null
        }
        Insert: {
          branch?: string | null
          dispatch_cap?: number | null
          dispatches_used?: number | null
          ended_at?: string | null
          engagement_id: string
          gates?: Json
          id?: string
          mode?: string | null
          run_id: string
          started_at?: string | null
          tests_failed?: number | null
          tests_passed?: number | null
          tests_skipped?: number | null
          verdict?: string | null
        }
        Update: {
          branch?: string | null
          dispatch_cap?: number | null
          dispatches_used?: number | null
          ended_at?: string | null
          engagement_id?: string
          gates?: Json
          id?: string
          mode?: string | null
          run_id?: string
          started_at?: string | null
          tests_failed?: number | null
          tests_passed?: number | null
          tests_skipped?: number | null
          verdict?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fleet_run_engagement_id_fkey"
            columns: ["engagement_id"]
            isOneToOne: false
            referencedRelation: "engagement"
            referencedColumns: ["id"]
          },
        ]
      }
      open_question: {
        Row: {
          answer: string | null
          answered_at: string | null
          answered_by: string | null
          best_guess: string | null
          confidence: Database["public"]["Enums"]["question_confidence"] | null
          engagement_id: string
          id: string
          question: string | null
          run: string | null
          section: string | null
          source_key: string | null
          status: Database["public"]["Enums"]["question_status"]
          unit: string | null
        }
        Insert: {
          answer?: string | null
          answered_at?: string | null
          answered_by?: string | null
          best_guess?: string | null
          confidence?: Database["public"]["Enums"]["question_confidence"] | null
          engagement_id: string
          id?: string
          question?: string | null
          run?: string | null
          section?: string | null
          source_key?: string | null
          status?: Database["public"]["Enums"]["question_status"]
          unit?: string | null
        }
        Update: {
          answer?: string | null
          answered_at?: string | null
          answered_by?: string | null
          best_guess?: string | null
          confidence?: Database["public"]["Enums"]["question_confidence"] | null
          engagement_id?: string
          id?: string
          question?: string | null
          run?: string | null
          section?: string | null
          source_key?: string | null
          status?: Database["public"]["Enums"]["question_status"]
          unit?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "open_question_engagement_id_fkey"
            columns: ["engagement_id"]
            isOneToOne: false
            referencedRelation: "engagement"
            referencedColumns: ["id"]
          },
        ]
      }
      operator: {
        Row: {
          created_at: string
          display_name: string | null
          email: string
          id: string
          mfa_enrolled_at: string | null
          role: string | null
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          email: string
          id: string
          mfa_enrolled_at?: string | null
          role?: string | null
        }
        Update: {
          created_at?: string
          display_name?: string | null
          email?: string
          id?: string
          mfa_enrolled_at?: string | null
          role?: string | null
        }
        Relationships: []
      }
      release: {
        Row: {
          deployed_at: string | null
          engagement_id: string
          environment: string
          id: string
          identifier: string
          recorded_by: string | null
          source: Database["public"]["Enums"]["release_source"]
          url: string | null
        }
        Insert: {
          deployed_at?: string | null
          engagement_id: string
          environment: string
          id?: string
          identifier: string
          recorded_by?: string | null
          source: Database["public"]["Enums"]["release_source"]
          url?: string | null
        }
        Update: {
          deployed_at?: string | null
          engagement_id?: string
          environment?: string
          id?: string
          identifier?: string
          recorded_by?: string | null
          source?: Database["public"]["Enums"]["release_source"]
          url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "release_engagement_id_fkey"
            columns: ["engagement_id"]
            isOneToOne: false
            referencedRelation: "engagement"
            referencedColumns: ["id"]
          },
        ]
      }
      release_requirement: {
        Row: {
          id: string
          release_id: string
          requirement_ref: string
        }
        Insert: {
          id?: string
          release_id: string
          requirement_ref: string
        }
        Update: {
          id?: string
          release_id?: string
          requirement_ref?: string
        }
        Relationships: [
          {
            foreignKeyName: "release_requirement_release_id_fkey"
            columns: ["release_id"]
            isOneToOne: false
            referencedRelation: "release"
            referencedColumns: ["id"]
          },
        ]
      }
      requirement: {
        Row: {
          engagement_id: string
          id: string
          ref: string
          section: string | null
          text: string | null
        }
        Insert: {
          engagement_id: string
          id?: string
          ref: string
          section?: string | null
          text?: string | null
        }
        Update: {
          engagement_id?: string
          id?: string
          ref?: string
          section?: string | null
          text?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "requirement_engagement_id_fkey"
            columns: ["engagement_id"]
            isOneToOne: false
            referencedRelation: "engagement"
            referencedColumns: ["id"]
          },
        ]
      }
      stack: {
        Row: {
          agent_covering: string | null
          first_seen_at: string | null
          id: string
          last_seen_at: string | null
          name: string
        }
        Insert: {
          agent_covering?: string | null
          first_seen_at?: string | null
          id?: string
          last_seen_at?: string | null
          name: string
        }
        Update: {
          agent_covering?: string | null
          first_seen_at?: string | null
          id?: string
          last_seen_at?: string | null
          name?: string
        }
        Relationships: []
      }
      test_case: {
        Row: {
          authored_by: string | null
          certified_by: string | null
          covers: string[]
          engagement_id: string
          file: string
          harness: Database["public"]["Enums"]["test_harness"]
          id: string
          title: string
        }
        Insert: {
          authored_by?: string | null
          certified_by?: string | null
          covers?: string[]
          engagement_id: string
          file: string
          harness: Database["public"]["Enums"]["test_harness"]
          id?: string
          title: string
        }
        Update: {
          authored_by?: string | null
          certified_by?: string | null
          covers?: string[]
          engagement_id?: string
          file?: string
          harness?: Database["public"]["Enums"]["test_harness"]
          id?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "test_case_engagement_id_fkey"
            columns: ["engagement_id"]
            isOneToOne: false
            referencedRelation: "engagement"
            referencedColumns: ["id"]
          },
        ]
      }
      test_result: {
        Row: {
          certified_by: string | null
          evidence_ref: string | null
          evidence_scope: Database["public"]["Enums"]["evidence_scope"] | null
          id: string
          run_at: string
          status: Database["public"]["Enums"]["test_status"]
          test_case_id: string
        }
        Insert: {
          certified_by?: string | null
          evidence_ref?: string | null
          evidence_scope?: Database["public"]["Enums"]["evidence_scope"] | null
          id?: string
          run_at?: string
          status?: Database["public"]["Enums"]["test_status"]
          test_case_id: string
        }
        Update: {
          certified_by?: string | null
          evidence_ref?: string | null
          evidence_scope?: Database["public"]["Enums"]["evidence_scope"] | null
          id?: string
          run_at?: string
          status?: Database["public"]["Enums"]["test_status"]
          test_case_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "test_result_test_case_id_fkey"
            columns: ["test_case_id"]
            isOneToOne: false
            referencedRelation: "test_case"
            referencedColumns: ["id"]
          },
        ]
      }
      work_item: {
        Row: {
          blocker_id: string | null
          description: string | null
          disposition: Database["public"]["Enums"]["work_disposition"] | null
          ended_at: string | null
          engagement_id: string
          evidence_scope: Database["public"]["Enums"]["evidence_scope"] | null
          execution_mode: Database["public"]["Enums"]["execution_mode"]
          executor: string | null
          executor_kind: Database["public"]["Enums"]["executor_kind"]
          external_wait_id: string | null
          fleet_run_id: string | null
          id: string
          not_verified_count: number
          phase: number | null
          raw_status: string | null
          stack_id: string | null
          started_at: string | null
          status: Database["public"]["Enums"]["work_status"]
          unautomated_reason:
            | Database["public"]["Enums"]["unautomated_reason"]
            | null
          unit: string | null
          work_type: string | null
        }
        Insert: {
          blocker_id?: string | null
          description?: string | null
          disposition?: Database["public"]["Enums"]["work_disposition"] | null
          ended_at?: string | null
          engagement_id: string
          evidence_scope?: Database["public"]["Enums"]["evidence_scope"] | null
          execution_mode: Database["public"]["Enums"]["execution_mode"]
          executor?: string | null
          executor_kind?: Database["public"]["Enums"]["executor_kind"]
          external_wait_id?: string | null
          fleet_run_id?: string | null
          id?: string
          not_verified_count?: number
          phase?: number | null
          raw_status?: string | null
          stack_id?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["work_status"]
          unautomated_reason?:
            | Database["public"]["Enums"]["unautomated_reason"]
            | null
          unit?: string | null
          work_type?: string | null
        }
        Update: {
          blocker_id?: string | null
          description?: string | null
          disposition?: Database["public"]["Enums"]["work_disposition"] | null
          ended_at?: string | null
          engagement_id?: string
          evidence_scope?: Database["public"]["Enums"]["evidence_scope"] | null
          execution_mode?: Database["public"]["Enums"]["execution_mode"]
          executor?: string | null
          executor_kind?: Database["public"]["Enums"]["executor_kind"]
          external_wait_id?: string | null
          fleet_run_id?: string | null
          id?: string
          not_verified_count?: number
          phase?: number | null
          raw_status?: string | null
          stack_id?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["work_status"]
          unautomated_reason?:
            | Database["public"]["Enums"]["unautomated_reason"]
            | null
          unit?: string | null
          work_type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "work_item_blocker_id_fkey"
            columns: ["blocker_id"]
            isOneToOne: false
            referencedRelation: "blocker"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_item_engagement_id_fkey"
            columns: ["engagement_id"]
            isOneToOne: false
            referencedRelation: "engagement"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_item_external_wait_id_fkey"
            columns: ["external_wait_id"]
            isOneToOne: false
            referencedRelation: "external_wait"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_item_fleet_run_id_fkey"
            columns: ["fleet_run_id"]
            isOneToOne: false
            referencedRelation: "fleet_run"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_item_stack_id_fkey"
            columns: ["stack_id"]
            isOneToOne: false
            referencedRelation: "stack"
            referencedColumns: ["id"]
          },
        ]
      }
      work_item_dependency: {
        Row: {
          depends_on_id: string
          id: string
          work_item_id: string
        }
        Insert: {
          depends_on_id: string
          id?: string
          work_item_id: string
        }
        Update: {
          depends_on_id?: string
          id?: string
          work_item_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "work_item_dependency_depends_on_id_fkey"
            columns: ["depends_on_id"]
            isOneToOne: false
            referencedRelation: "work_item"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_item_dependency_work_item_id_fkey"
            columns: ["work_item_id"]
            isOneToOne: false
            referencedRelation: "work_item"
            referencedColumns: ["id"]
          },
        ]
      }
      work_item_requirement: {
        Row: {
          id: string
          requirement_ref: string
          work_item_id: string
        }
        Insert: {
          id?: string
          requirement_ref: string
          work_item_id: string
        }
        Update: {
          id?: string
          requirement_ref?: string
          work_item_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "work_item_requirement_work_item_id_fkey"
            columns: ["work_item_id"]
            isOneToOne: false
            referencedRelation: "work_item"
            referencedColumns: ["id"]
          },
        ]
      }
      work_session: {
        Row: {
          commits: number | null
          duration_minutes: number | null
          ended_at: string | null
          engagement_id: string
          files_changed: number | null
          id: string
          source: string | null
          stack_id: string | null
          started_at: string
          summary: string | null
          work_item_id: string | null
          working_directory: string | null
        }
        Insert: {
          commits?: number | null
          duration_minutes?: number | null
          ended_at?: string | null
          engagement_id: string
          files_changed?: number | null
          id?: string
          source?: string | null
          stack_id?: string | null
          started_at: string
          summary?: string | null
          work_item_id?: string | null
          working_directory?: string | null
        }
        Update: {
          commits?: number | null
          duration_minutes?: number | null
          ended_at?: string | null
          engagement_id?: string
          files_changed?: number | null
          id?: string
          source?: string | null
          stack_id?: string | null
          started_at?: string
          summary?: string | null
          work_item_id?: string | null
          working_directory?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "work_session_engagement_id_fkey"
            columns: ["engagement_id"]
            isOneToOne: false
            referencedRelation: "engagement"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_session_stack_id_fkey"
            columns: ["stack_id"]
            isOneToOne: false
            referencedRelation: "stack"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_session_work_item_id_fkey"
            columns: ["work_item_id"]
            isOneToOne: false
            referencedRelation: "work_item"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      check_and_increment_rate_limit: {
        Args: { p_limit: number; p_token_id: string; p_window_seconds: number }
        Returns: boolean
      }
      decrypt_field: { Args: { ciphertext: string }; Returns: string }
      encrypt_field: { Args: { plaintext: string }; Returns: string }
      hash_agent_token: { Args: { p_token: string }; Returns: string }
      prune_rate_limit_counters: {
        Args: { p_older_than?: string }
        Returns: number
      }
      verify_agent_token: {
        Args: { p_hash: string; p_token: string }
        Returns: boolean
      }
    }
    Enums: {
      actor_type: "operator" | "agent" | "system"
      agent_capability: "answer_read" | "ingest_write"
      defect_severity: "critical" | "major" | "minor" | "unparsed"
      defect_source: "qa_agent" | "operator" | "client" | "api"
      defect_status: "open" | "fixed" | "verified" | "wont_fix" | "unparsed"
      evidence_scope:
        | "observed_live"
        | "observed_elsewhere"
        | "asserted"
        | "not_verified"
      execution_mode: "fleet" | "hand" | "external"
      executor_kind:
        | "agent"
        | "erik"
        | "erik_gate"
        | "client"
        | "vendor"
        | "unassigned"
      question_confidence: "low" | "med" | "high"
      question_status: "open" | "answered"
      release_source: "declared" | "ingested"
      test_harness: "vitest" | "playwright" | "database_probe"
      test_status: "pass" | "fail" | "skipped" | "unparsed"
      unautomated_reason:
        | "no_agent_for_stack"
        | "credential_absent"
        | "human_judgment"
        | "client_action"
        | "out_of_scope"
        | "budget"
      wait_resolution_method: "probe" | "manual"
      work_disposition: "carried" | "closed"
      work_status:
        | "pending"
        | "in_flight"
        | "done"
        | "blocked"
        | "superseded"
        | "not_dispatched"
        | "unparsed"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      actor_type: ["operator", "agent", "system"],
      agent_capability: ["answer_read", "ingest_write"],
      defect_severity: ["critical", "major", "minor", "unparsed"],
      defect_source: ["qa_agent", "operator", "client", "api"],
      defect_status: ["open", "fixed", "verified", "wont_fix", "unparsed"],
      evidence_scope: [
        "observed_live",
        "observed_elsewhere",
        "asserted",
        "not_verified",
      ],
      execution_mode: ["fleet", "hand", "external"],
      executor_kind: [
        "agent",
        "erik",
        "erik_gate",
        "client",
        "vendor",
        "unassigned",
      ],
      question_confidence: ["low", "med", "high"],
      question_status: ["open", "answered"],
      release_source: ["declared", "ingested"],
      test_harness: ["vitest", "playwright", "database_probe"],
      test_status: ["pass", "fail", "skipped", "unparsed"],
      unautomated_reason: [
        "no_agent_for_stack",
        "credential_absent",
        "human_judgment",
        "client_action",
        "out_of_scope",
        "budget",
      ],
      wait_resolution_method: ["probe", "manual"],
      work_disposition: ["carried", "closed"],
      work_status: [
        "pending",
        "in_flight",
        "done",
        "blocked",
        "superseded",
        "not_dispatched",
        "unparsed",
      ],
    },
  },
} as const
